Program 0x15
AreaSettings 82 -1
	SetJump Type 2 World AL Area 0 Entrance 0 LocalSet 110 FadeType 1
	SetPartyMenu 0

AreaSettings 161 -1
	SetUnk05 0x1
	SetJump Type 2 World HB Area 0 Entrance 0 LocalSet 122 FadeType 1
	SetPartyMenu 0

AreaSettings 162 -1
	SetUnk05 0x1
	SetJump Type 2 World HB Area 0 Entrance 0 LocalSet 132 FadeType 1
	SetPartyMenu 0

Spawn "e_01"
Spawn "r_29"
Spawn "a54y"
Spawn "r_20"
Spawn "z00s"
