Program 0x10
Unk0e 1
MapVisibility 0x000c1c8f 0x00000000
Spawn "m_00"
Spawn "m_10"
Spawn "m_11"
Spawn "m_20"
Spawn "m_22"
Spawn "m_50"
Spawn "m_70"
Spawn "m_71"
Spawn "m_82"
Spawn "m_84"
Spawn "m_90"
Spawn "m_92"

Program 0x11
Unk0e 1
MapVisibility 0x000c1c8f 0x00000000
Spawn "m_01"
Spawn "m_10"
Spawn "m_11"
Spawn "m_20"
SpawnAlt "m_21"
Spawn "m_22"
Spawn "m_50"
Spawn "m_70"
Spawn "m_71"
Spawn "m_82"
Spawn "m_84"
Spawn "m_90"
Spawn "m_92"
