Program 0x01
Party DEFAULT
Bgm Default Default
AreaSettings 0 -1
	SetProgressFlag 0x1001
	SetEvent "101" Type 2
	SetJump Type 1 World HB Area 0 Entrance 0 LocalSet 0 FadeType 1
	SetPartyMenu 0

Program 0x02
Party DEFAULT
Bgm Default Default
AreaSettings 0 -1
	SetProgressFlag 0x102E
	SetEvent "801" Type 2
	SetJump Type 1 World HB Area 10 Entrance 0 LocalSet 0 FadeType 1
	SetPartyMenu 0

Spawn "e_01"
