Program 0x01
Party DEFAULT
Bgm Default Default
AreaSettings 0 -1
	SetProgressFlag 0x440A
	SetUnk05 0x1
	SetEvent "109" Type 2
	SetJump Type 1 World TR Area 2 Entrance 0 LocalSet 0 FadeType 1
	SetPartyMenu 0

Spawn "e_02"

Program 0x02
Party DEFAULT
Bgm 85 85
AreaSettings 0 -1
	SetProgressFlag 0x442B
	SetEvent "118" Type 2
	SetJump Type 1 World TR Area 0 Entrance 0 LocalSet 0 FadeType 1
	SetPartyMenu 0
